# Generated by Django 4.2.23 on 2025-09-03 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemPrompts',
            new_name='SystemPrompt',
        ),
    ]
