# from gradio_client import Client, file

# client = Client("http://192.168.50.60:42004/")
import json
import requests
from pprint import pprint as pp


d = dict(
  text_input="Hello! This is a demonstration of the ultimate TTS studio. You can choose between Chatterbox TTS. Fish Speech, VoxCPM, Index TTS and Index TTS 2, Higgs audio TTS and F5 TTS for custom voice cloning or Kitten TTS and Kokoro TTS for high-quality pre-trained voices and VibeVoice for podcast.",
  tts_engine="Kokoro TTS",
  audio_format="wav",
  chatterbox_ref_audio=None,
  chatterbox_exaggeration=0.5,
  chatterbox_temperature=0.8,
  chatterbox_cfg_weight=0.5,
  chatterbox_chunk_size=300,
  chatterbox_seed=0,
  chatterbox_mtl_ref_audio=None,
  chatterbox_mtl_language="en",
  chatterbox_mtl_exaggeration=0.5,
  chatterbox_mtl_temperature=0.8,
  chatterbox_mtl_cfg_weight=0.5,
  chatterbox_mtl_repetition_penalty=2,
  chatterbox_mtl_min_p=0.05,
  chatterbox_mtl_top_p=1,
  chatterbox_mtl_chunk_size=300,
  chatterbox_mtl_seed=0,
  kokoro_voice="af_bella",
  kokoro_speed=1,
  fish_ref_audio=None,
  fish_ref_text="",
  fish_temperature=0.8,
  fish_top_p=0.8,
  fish_repetition_penalty=1.1,
  fish_max_tokens=1024,
  fish_seed=0,
  indextts_ref_audio=None,
  indextts_temperature=0.8,
  indextts_seed=0,
  indextts2_ref_audio=None,
  indextts2_emotion_mode="audio_reference",
  indextts2_emotion_audio=None,
  indextts2_emotion_description="",
  indextts2_emo_alpha=1,
  indextts2_happy=0,
  indextts2_angry=0,
  indextts2_sad=0,
  indextts2_afraid=0,
  indextts2_disgusted=0,
  indextts2_melancholic=0,
  indextts2_surprised=0,
  indextts2_calm=1,
  indextts2_temperature=0.8,
  indextts2_top_p=0.9,
  indextts2_top_k=50,
  indextts2_repetition_penalty=1.1,
  indextts2_max_mel_tokens=1500,
  indextts2_seed=0,
  indextts2_use_random=False,
  f5_ref_audio=None,
  f5_ref_text="",
  f5_speed=1,
  f5_cross_fade=0.15,
  f5_remove_silence=False,
  f5_seed=0,
  higgs_ref_audio=None,
  higgs_ref_text="",
  higgs_voice_preset="EMPTY",
  higgs_system_prompt="",
  higgs_temperature=1,
  higgs_top_p=0.95,
  higgs_top_k=50,
  higgs_max_tokens=1024,
  higgs_ras_win_len=7,
  higgs_ras_win_max_num_repeat=2,
  kitten_voice="expr-voice-2-f",
  voxcpm_ref_audio=None,
  voxcpm_ref_text="",
  voxcpm_cfg_value=2,
  voxcpm_inference_timesteps=10,
  voxcpm_normalize=True,
  voxcpm_denoise=True,
  voxcpm_retry_badcase=True,
  voxcpm_retry_badcase_max_times=3,
  voxcpm_retry_badcase_ratio_threshold=6,
  voxcpm_seed=-1,
  gain_db=0,
  enable_eq=False,
  eq_bass=0,
  eq_mid=0,
  eq_treble=0,
  enable_reverb=False,
  reverb_room=0.3,
  reverb_damping=0.5,
  reverb_wet=0.3,
  enable_echo=False,
  echo_delay=0.3,
  echo_decay=0.5,
  enable_pitch=False,
  pitch_semitones=0,
  # api_name="/generate_unified_tts"
)


url = "http://192.168.50.60:42004/gradio_api/call/generate_unified_tts"
headers = {
    'Content-Type': "application/json",
    'Accept': "*/*",
    # "Authorization":f"Bearer {AGENT_ACCESS_KEY}",
    'Cache-Control': "no-cache",
}
data = {
        "data": list(d.values())
    }
data = json.dumps(data)
print(url)
response = requests.request("POST", url, data=data, headers=headers)
content = response.json()
pp(content)

"""

good:
    {'event_id': 'f18b627edf8d48b4813b322fcd354c3f'}

bad:

    http://192.168.50.60:42004/gradio_api/call/generate_unified_tts
    {'detail': [{'input': ['text_input',
                           'tts_engine',
                           'audio_format',
                           'chatterbox_ref_audio',
                           'chatterbox_exaggeration',
                           'chatterbox_temperature',
                           'chatterbox_cfg_weight',
                           'chatterbox_chunk_size',
                           'chatterbox_seed',
                           'chatterbox_mtl_ref_audio',
                           'chatterbox_mtl_language',
                           'chatterbox_mtl_exaggeration',
                           'chatterbox_mtl_temperature',
                           'chatterbox_mtl_cfg_weight',
                           'chatterbox_mtl_repetition_penalty',
                           'chatterbox_mtl_min_p',
                           'chatterbox_mtl_top_p',
                           'chatterbox_mtl_chunk_size',
                           'chatterbox_mtl_seed',
                           'kokoro_voice',
                           'kokoro_speed',
                           'fish_ref_audio',
                           'fish_ref_text',
                           'fish_temperature',
                           'fish_top_p',
                           'fish_repetition_penalty',
                           'fish_max_tokens',
                           'fish_seed',
                           'indextts_ref_audio',
                           'indextts_temperature',
                           'indextts_seed',
                           'indextts2_ref_audio',
                           'indextts2_emotion_mode',
                           'indextts2_emotion_audio',
                           'indextts2_emotion_description',
                           'indextts2_emo_alpha',
                           'indextts2_happy',
                           'indextts2_angry',
                           'indextts2_sad',
                           'indextts2_afraid',
                           'indextts2_disgusted',
                           'indextts2_melancholic',
                           'indextts2_surprised',
                           'indextts2_calm',
                           'indextts2_temperature',
                           'indextts2_top_p',
                           'indextts2_top_k',
                           'indextts2_repetition_penalty',
                           'indextts2_max_mel_tokens',
                           'indextts2_seed',
                           'indextts2_use_random',
                           'f5_ref_audio',
                           'f5_ref_text',
                           'f5_speed',
                           'f5_cross_fade',
                           'f5_remove_silence',
                           'f5_seed',
                           'higgs_ref_audio',
                           'higgs_ref_text',
                           'higgs_voice_preset',
                           'higgs_system_prompt',
                           'higgs_temperature',
                           'higgs_top_p',
                           'higgs_top_k',
                           'higgs_max_tokens',
                           'higgs_ras_win_len',
                           'higgs_ras_win_max_num_repeat',
                           'kitten_voice',
                           'voxcpm_ref_audio',
                           'voxcpm_ref_text',
                           'voxcpm_cfg_value',
                           'voxcpm_inference_timesteps',
                           'voxcpm_normalize',
                           'voxcpm_denoise',
                           'voxcpm_retry_badcase',
                           'voxcpm_retry_badcase_max_times',
                           'voxcpm_retry_badcase_ratio_threshold',
                           'voxcpm_seed',
                           'gain_db',
                           'enable_eq',
                           'eq_bass',
                           'eq_mid',
                           'eq_treble',
                           'enable_reverb',
                           'reverb_room',
                           'reverb_damping',
                           'reverb_wet',
                           'enable_echo',
                           'echo_delay',
                           'echo_decay',
                           'enable_pitch',
                           'pitch_semitones'],
                 'loc': ['body'],
                 'msg': 'Input should be a valid dictionary or object to extract '
                        'fields from',
             'type': 'model_attributes_type'}]}
"""

eid = content['event_id']
eurl = f'{url}/{eid}'
print(url)
response = requests.request("GET", eurl, headers=headers)
content = response.text
print(content)
